project:
  type: website
  output-dir: docs
  
website:
  title: "Aditya Website"
  navbar: 
    left:
      - index.qmd
      - Introduction.qmd
      - about.qmd
      
format:
  html:
    theme: cosmo